Repository ICT4Dat/ict4dat-news-android, pull requests merged in 2018-10, with the labels that each got.

#80 Feat blog and sources
  ICT4DNews/app/room_schemas/at.ict4d.ict4dnews.persistence.database.AppDatabase/1.json
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/DaggerViewModelHelper.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/activities/MainNavigationActivityModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/models/Author.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/models/Blog.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/models/News.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/database/dao/BlogDao.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/database/dao/NewsDao.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/MainNavigationActivity.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/base/BaseFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/ict4d/TabbedICT4DFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/ict4d/ict4d/ICT4DFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/ict4d/ict4dat/ICT4DatFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/more/MoreFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceViewModel.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailActivity.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsViewModel.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/server/Server.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/utils/RXBusMessages.kt
  ICT4DNews/app/src/main/res/layout/blog_and_source_item.xml
  ICT4DNews/app/src/main/res/layout/fragment_blog_and_sources.xml
  ICT4DNews/app/src/main/res/menu/ict4dnews_menu.xml
  ICT4DNews/app/src/main/res/navigation/nav_graph.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  server/ict4d_blogs.php
Labels: enhancement

#83 Fixes #79 - Improve Dagger
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/activities/BaseActivityModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/activities/ICT4DNewsDetailActivityModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/activities/MainNavigationActivityModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/fragments/ICT4DNewsFragmentModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/fragments/ICT4DatFragmentModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/fragments/MoreFragmentModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/fragments/TabbedICT4DFragmentModule.kt
  ICT4DNews/build.gradle
Labels: enhancement

#88 Fixes #87 - Fix Blogs And Source CheckBox OnClick
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceRecyclerViewAdapter.kt
Labels: bug

#82 Refs #33 - Change Design of News Item
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/HelperModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/RoomModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/database/dao/BlogDao.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/database/dao/NewsDao.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/sharedpreferences/ISharedPrefs.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/sharedpreferences/SharedPrefs.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailActivity.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsViewModel.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/server/Server.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/utils/AppGlideModule.kt
  ICT4DNews/app/src/main/res/drawable/ic_broken_image_black_24dp.xml
  ICT4DNews/app/src/main/res/drawable/ic_error_black_24dp.xml
  ICT4DNews/app/src/main/res/drawable/ic_refresh_black_24dp.xml
  ICT4DNews/app/src/main/res/layout/blog_and_source_item.xml
  ICT4DNews/app/src/main/res/layout/fragment_ictdnews_item.xml
  ICT4DNews/app/src/main/res/values/preferences.xml
  ICT4DNews/build.gradle
  server/ict4d_blogs.php
Labels: enhancement

#90 fixes #76 - strips HTML from headlines and improves DB insertion
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/dagger/modules/RoomModule.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/models/News.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/server/Server.kt
Labels: bug, enhancement

#91 Feat date label fix and links in webview
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailFragment.kt
  ICT4DNews/app/src/main/res/layout/fragment_ict4_dnews_detail.xml
Labels: bug, enhancement

#92 fixes #85 - adds pull to refresh to blogs
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceViewModel.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/server/Server.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/utils/RXBusMessages.kt
  ICT4DNews/app/src/main/res/layout/fragment_blog_and_sources.xml
Labels: enhancement

#93 fixes #66 and #72 - more settings screen and licences
  .travis.yml
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/more/MoreFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/res/drawable-hdpi/chloe.jpg
  ICT4DNews/app/src/main/res/drawable-hdpi/paul.jpg
  ICT4DNews/app/src/main/res/drawable-mdpi/chloe.jpg
  ICT4DNews/app/src/main/res/drawable-mdpi/paul.jpg
  ICT4DNews/app/src/main/res/drawable-xhdpi/chloe.jpg
  ICT4DNews/app/src/main/res/drawable-xhdpi/paul.jpg
  ICT4DNews/app/src/main/res/drawable-xxhdpi/chloe.jpg
  ICT4DNews/app/src/main/res/drawable-xxhdpi/paul.jpg
  ICT4DNews/app/src/main/res/drawable-xxxhdpi/chloe.jpg
  ICT4DNews/app/src/main/res/drawable-xxxhdpi/paul.jpg
  ICT4DNews/app/src/main/res/layout/fragment_more.xml
  ICT4DNews/app/src/main/res/menu/ict4dnews_menu.xml
  ICT4DNews/app/src/main/res/menu/menu_more_settings.xml
  ICT4DNews/app/src/main/res/values-de/custom_strings.xml
  ICT4DNews/app/src/main/res/values-de/links.xml
  ICT4DNews/app/src/main/res/values-v21/styles.xml
  ICT4DNews/app/src/main/res/values/custom_strings.xml
  ICT4DNews/app/src/main/res/values/ids.xml
  ICT4DNews/app/src/main/res/values/links.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/build.gradle
Labels: enhancement

#97 Fixes #96 - Fix Pull To Refresh Bug In News Fragment
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
Labels: bug

#98 Update README.md
  README.md
Labels: enhancement

#102 fixes #101 - adds version for server
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/server/ApiICT4DatNews.kt
Labels: enhancement

#111 Fixes #99 - Added my profile picture to more screen
  ICT4DNews/app/src/main/res/drawable-hdpi/noah.jpg
  ICT4DNews/app/src/main/res/drawable-mdpi/noah.jpg
  ICT4DNews/app/src/main/res/drawable-xhdpi/noah.jpg
  ICT4DNews/app/src/main/res/drawable-xxhdpi/noah.jpg
  ICT4DNews/app/src/main/res/drawable-xxxhdpi/noah.jpg
  ICT4DNews/app/src/main/res/layout/fragment_more.xml
Labels: enhancement

#112 updates and last changes before first alpha release
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/res/layout/fragment_ict4d.xml
  ICT4DNews/app/src/main/res/values/custom_strings.xml
Labels: enhancement

#114 fixes #113 - removes donation buttons
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/ict4d/ict4dat/ICT4DatFragment.kt
  ICT4DNews/app/src/main/java/at/ict4d/ict4dnews/screens/splashscreen/SplashFragment.kt
  ICT4DNews/app/src/main/res/layout/fragment_ict4dat.xml
  ICT4DNews/app/src/main/res/layout/fragment_more.xml
  ICT4DNews/app/src/main/res/layout/fragment_splash.xml
  ICT4DNews/app/src/main/res/values-de/strings.xml
  ICT4DNews/app/src/main/res/values/custom_strings.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/app/tasks.gradle
  ICT4DNews/build.gradle
Labels: bug, enhancement
