Repository ICT4Dat/ict4dat-news-android, pull requests merged in 2019-03, with the labels that each got.

#154 Paging Lib
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/HelperModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/dao/BlogDao.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/dao/NewsDao.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailViewModel.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsViewModel.kt
  ICT4DNews/app/src/main/res/layout/fragment_ictdnews_item.xml
  ICT4DNews/app/src/main/res/layout/fragment_ictdnews_list.xml
  ICT4DNews/build.gradle
Labels: enhancement

#141 Refs #122 - Feat new news badge
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/models/Author.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/sharedpreferences/SharedPrefs.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsViewModel.kt
  ICT4DNews/app/src/main/res/drawable/ic_fiber_new_black_24dp.xml
  ICT4DNews/app/src/main/res/layout/fragment_ictdnews_item.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/build.gradle
Labels: Future Release, enhancement

#149 Refs #147 - Dagger Improvements
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/ICT4DNewsApplication.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/ApiServiceModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/DaggerViewModelHelper.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/HelperModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/RoomModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/sharedpreferences/SharedPrefs.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/MainNavigationActivity.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/base/BaseFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/server/Server.kt
Labels: Future Release, enhancement

#148 Refs #125 - Add Setting Screen
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/background/UpdateNewsServiceHandler.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/components/ApplicationComponent.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/DaggerViewModelHelper.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/activities/MainNavigationActivityModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/sharedpreferences/ISharedPrefs.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/sharedpreferences/SharedPrefs.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/MainNavigationViewModel.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/MoreFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/settings/SettingsFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/settings/SettingsFragmentWithToolbar.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/settings/SettingsWithToolbarViewModel.kt
  ICT4DNews/app/src/main/res/drawable/ic_settings_white_24dp.xml
  ICT4DNews/app/src/main/res/layout/fragment_settings_with_toolbar.xml
  ICT4DNews/app/src/main/res/menu/menu_more_settings.xml
  ICT4DNews/app/src/main/res/navigation/nav_graph.xml
  ICT4DNews/app/src/main/res/values-de/strings.xml
  ICT4DNews/app/src/main/res/values/preferences.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/app/src/main/res/xml/setting_preferences.xml
Labels: Future Release, enhancement

#162 Adds new sources and fixes some critical bugs
  ICT4DNews/app/room_schemas/at.ict4d.ict4dnews.persistence.database.AppDatabase/2.json
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/RoomModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/AppDatabase.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/migrations/Migration1to2.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/server/ApiICT4DatNews.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/server/Server.kt
  README.md
  server/ict4d_blogs.php
Labels: Future Release, bug, enhancement

#155 DAO Unit Tests
  .travis.yml
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/ICT4DNewsApplication.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/models/Author.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/dao/AuthorDao.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/dao/BlogDao.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/dao/MediaDao.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/database/dao/NewsDao.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailViewModel.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsViewModel.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/TestICT4DNewsApplication.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/dao/AuthorDaoTests.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/dao/BaseDaoTest.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/dao/BlogDaoTests.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/dao/MediaDaoTests.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/dao/NewsDaoTests.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/utils/AuthorTestUtils.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/utils/BaseTestUtils.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/utils/BlogTestUtils.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/utils/LiveDataTestUtil.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/utils/MediaTestUtils.kt
  ICT4DNews/app/src/test/kotlin/at/ict4d/ict4dnews/utils/NewsTestUtils.kt
  ICT4DNews/build.gradle
  ICT4DNews/gradle.properties
Labels: Future Release, enhancement, good first issue, help wanted
