Repository ICT4Dat/ict4dat-news-android, pull requests merged in 2019-04, with the labels that each got.

#164 Updates ICT4D.at information and adds social media buttons
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/ict4d/ict4dat/ICT4DatFragment.kt
  ICT4DNews/app/src/main/res/drawable/ic_facebook.xml
  ICT4DNews/app/src/main/res/drawable/ic_mastodon.xml
  ICT4DNews/app/src/main/res/drawable/ic_twitter.xml
  ICT4DNews/app/src/main/res/layout/fragment_ict4d.xml
  ICT4DNews/app/src/main/res/layout/fragment_ict4dat.xml
  ICT4DNews/app/src/main/res/values-de/strings.xml
  ICT4DNews/app/src/main/res/values/custom_strings.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/app/src/main/res/values/styles.xml
Labels: Future Release, enhancement

#168 refs #159 - adds fast scroll lib and implementation
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsRecyclerViewAdapter.kt
  ICT4DNews/app/src/main/res/layout/fragment_ictdnews_list.xml
Labels: enhancement

#166 refs #165 - adds release signing and introduces new Version Code hand…
  ICT4DNews/.gitignore
  ICT4DNews/app/build.gradle
  ICT4DNews/app/play-store-publisher-config.gradle
  ICT4DNews/app/release-sign-credentials.gradle
  ICT4DNews/app/src/main/play/contact-email.txt
  ICT4DNews/app/src/main/play/contact-website.txt
  ICT4DNews/app/src/main/play/default-language.txt
  ICT4DNews/app/src/main/play/listings/en-GB/full-description.txt
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/feature-graphic/6064268857038076582.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/1891683558090681892.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/6831054363113826409.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/8191374084150504192.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/9314037374704005173.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/9406580733645089521.png
  ICT4DNews/app/src/main/play/listings/en-GB/short-description.txt
  ICT4DNews/app/src/main/play/listings/en-GB/title.txt
  ICT4DNews/app/src/main/play/release-notes/en-GB/default.txt
  ICT4DNews/app/src/main/play/release-notes/en-GB/production.txt
  ICT4DNews/build.gradle
Labels: enhancement

#167 Fixes #161 - Fixed News List Multiple Taps Bug
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/MoreFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/res/menu/navigation.xml
  ICT4DNews/app/src/main/res/navigation/nav_graph.xml
Labels: bug

#170 fixes #169 - updates Dagger to latest version and resolves deprecated…
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/ICT4DNewsApplication.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/components/ApplicationComponent.kt
  ICT4DNews/build.gradle
Labels: enhancement

#175 fixes #174 - updates Play Store listings and prepares v1.1.0 release
  ICT4DNews/app/src/main/play/listings/de-DE/full-description.txt
  ICT4DNews/app/src/main/play/listings/de-DE/graphics/phone-screenshots/1.png
  ICT4DNews/app/src/main/play/listings/de-DE/graphics/phone-screenshots/2.png
  ICT4DNews/app/src/main/play/listings/de-DE/graphics/phone-screenshots/3.png
  ICT4DNews/app/src/main/play/listings/de-DE/graphics/phone-screenshots/4.png
  ICT4DNews/app/src/main/play/listings/de-DE/graphics/phone-screenshots/5.png
  ICT4DNews/app/src/main/play/listings/de-DE/short-description.txt
  ICT4DNews/app/src/main/play/listings/en-GB/full-description.txt
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/1.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/1891683558090681892.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/2.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/3.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/4.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/5.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/6831054363113826409.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/8191374084150504192.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/9314037374704005173.png
  ICT4DNews/app/src/main/play/listings/en-GB/graphics/phone-screenshots/9406580733645089521.png
Labels: enhancement

#173 Feat Sentry
  ICT4DNews/.gitignore
  ICT4DNews/app/build.gradle
  ICT4DNews/app/sentry-config.gradle
  ICT4DNews/app/src/main/AndroidManifest.xml
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/ICT4DNewsApplication.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/RoomModule.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/extensions/ICT4DExtensions.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/lifecycle/SentryLifecycleObserver.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/IPersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/PersistenceManager.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/sharedpreferences/ISharedPrefs.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/persistence/sharedpreferences/SharedPrefs.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/MainNavigationActivity.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/base/BaseFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/ict4d/TabbedICT4DFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/MoreFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/more/settings/SettingsFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/blogandsource/BlogAndSourceFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/detail/ICT4DNewsDetailFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/news/list/ICT4DNewsFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/screens/splashscreen/SplashFragment.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/server/Server.kt
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/utils/SentryHandler.kt
  ICT4DNews/app/src/main/play/release-notes/de-De/default.txt
  ICT4DNews/app/src/main/play/release-notes/en-GB/default.txt
  ICT4DNews/app/src/main/play/release-notes/en-GB/production.txt
  ICT4DNews/app/src/main/res/values-de/strings.xml
  ICT4DNews/app/src/main/res/values/preferences.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/app/src/main/res/xml/setting_preferences.xml
  ICT4DNews/build.gradle
Labels: enhancement

#179 fixes #178 - bumps versionBuild for release and shortens settings text
  ICT4DNews/app/src/main/play/listings/de-DE/full-description.txt
  ICT4DNews/app/src/main/play/listings/en-GB/full-description.txt
  ICT4DNews/app/src/main/play/release-notes/de-De/default.txt
  ICT4DNews/app/src/main/play/release-notes/en-GB/default.txt
  ICT4DNews/app/src/main/res/values-de/strings.xml
  ICT4DNews/app/src/main/res/values/strings.xml
  ICT4DNews/build.gradle
Labels: bug

#181 fixes #180 - sets back OKHttp since OkHttp 3.13+ requires API 21+
  ICT4DNews/app/build.gradle
  ICT4DNews/app/src/main/kotlin/at/ict4d/ict4dnews/dagger/modules/ApiServiceModule.kt
  ICT4DNews/app/src/main/play/release-notes/de-De/production.txt
  ICT4DNews/app/src/main/play/release-notes/en-GB/production.txt
  ICT4DNews/build.gradle
Labels: bug
